#!/usr/bin/env python3
from pathlib import Path

print(
    """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>sudoku-aid tests</title>
  <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.10.0.css">
</head>
<body>
  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
  <script src="https://code.jquery.com/qunit/qunit-2.10.0.js"></script>
"""
)

dist_path = Path(__file__).parent / "dist"
for test in sorted(dist_path.glob("**/*.test.js")):
    test_relative = test.relative_to(dist_path)
    print(f"""  <script type="module" src="{test_relative}"></script>""")

print(
    """\
</body>
</html>"""
)
